spring.application.name=SpringBoot_ApiKey
api.key=MY_SECRET_KEY_123
spring.datasource.url=jdbc:mysql://localhost:3306/apikeydb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true