spring.application.name=Cloudinary_Proj

CLOUDINARY_CLOUD_NAME=dft5d17m7
CLOUDINARY_API_KEY=623992728812711
CLOUDINARY_API_SECRET=1VF8r9Tyhs7WogOeliCToArGgxU

spring.datasource.url=jdbc:mysql://localhost:3306/cloudinarydb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
