spring.application.name=hotel-management

# Supabase Transaction Pooler
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.tsapkpdgqlymdqsvrptx
spring.datasource.password=Piyush@123xyz

supabase.url=https://tsapkpdgqlymdqsvrptx.supabase.co
supabase.api.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzYXBrcGRncWx5bWRxc3ZycHR4Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3OTUwMjkzNiwiZXhwIjoyMDk1MDc4OTM2fQ._53cPpgEd37CPnkTpu1oDPCt91g3SxazRjfu-wEiw3s
supabase.bucket=hotel

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Optional Hikari Settings
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=20000

app.jwt.secret=change-this-secret-key-change-this-secret-key
app.jwt.expiration-ms=3600000

spring.datasource.hikari.connection-init-sql=DISCARD ALL
spring.jpa.properties.hibernate.jdbc.prepare_sql=false