spring.application.name=externalApi

app.auth.url=https://api.supplier.roomdb.io/api/v1/suppliers/get-token
app.supplierId=booking_parser_properties_user
app.supplierSecret=R%qBn$4Zcn@84dSvyL9Azm
spring.datasource.url=jdbc:mysql://localhost:3306/externaldb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=SpringBootJwtAuthSecretKey-2026-XYZ!
jwt.expiration=3600000