spring.application.name=SendEmail

# SMTP Configuration
spring.mail.host=mail.electems.com
spring.mail.port=587
spring.mail.username=raveendra@electems.com
spring.mail.password=xvF60d5W4#

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=*
spring.mail.properties.mail.smtp.ssl.checkserveridentity=false